<?php require_once __DIR__ . '/../database/db.php'; session_start(); if (empty($_SESSION['user'])) { header('Location: login.php'); exit; } $msg=''; if ($_SERVER['REQUEST_METHOD']==='POST') { // add or edit
  $id = intval($_POST['id'] ?? 0); $category = $_POST['category'] ?? ''; $distance = $_POST['distance'] ?? ''; $fare = floatval($_POST['fare'] ?? 0); $unit = $_POST['unit'] ?? ''; $notes = $_POST['notes'] ?? '';
  if ($id) { $pdo->prepare('UPDATE tariffs SET category=?,distance=?,fare=?,unit=?,notes=? WHERE id=?')->execute([$category,$distance,$fare,$unit,$notes,$id]); $msg='Updated'; } else { $pdo->prepare('INSERT INTO tariffs (category,distance,fare,unit,notes) VALUES (?,?,?,?,?)')->execute([$category,$distance,$fare,$unit,$notes]); $msg='Added'; }
}
if (isset($_GET['delete'])) { $pdo->prepare('DELETE FROM tariffs WHERE id=?')->execute([intval($_GET['delete'])]); $msg='Deleted'; }
$tariffs = $pdo->query('SELECT * FROM tariffs ORDER BY category, distance')->fetchAll(PDO::FETCH_ASSOC);
?>
<!doctype html><html><head><meta charset='utf-8'><title>Manage Tariffs</title><link href='/public/css/bootstrap.min.css' rel='stylesheet'></head><body><div class='container py-4'><h3>Tariffs</h3><?php if($msg): ?><div class='alert alert-success'><?=htmlspecialchars($msg)?></div><?php endif; ?>
<div class='card p-3 mb-3'><form method='post'><input type='hidden' name='id' id='id'><div class='row'><div class='col-md-3'><input class='form-control' name='category' id='category' placeholder='Category (e.g., Sedan)' required></div><div class='col-md-2'><input class='form-control' name='distance' id='distance' placeholder='Distance (e.g., 0-10 km)' required></div><div class='col-md-2'><input class='form-control' name='fare' id='fare' placeholder='Fare' required></div><div class='col-md-2'><input class='form-control' name='unit' id='unit' placeholder='Unit (e.g., per km)'></div><div class='col-md-2'><input class='form-control' name='notes' id='notes' placeholder='Notes'></div><div class='col-md-1'><button class='btn btn-primary'>Save</button></div></div></form></div>
<table class='table table-sm'><thead><tr><th>ID</th><th>Category</th><th>Distance</th><th>Fare</th><th>Unit</th><th>Notes</th><th>Action</th></tr></thead><tbody><?php foreach($tariffs as $t): ?><tr><td><?=htmlspecialchars($t['id'])?></td><td><?=htmlspecialchars($t['category'])?></td><td><?=htmlspecialchars($t['distance'])?></td><td><?=htmlspecialchars($t['fare'])?></td><td><?=htmlspecialchars($t['unit'])?></td><td><?=htmlspecialchars($t['notes'])?></td><td><a class='btn btn-sm btn-outline-secondary' href='#' onclick='edit(<?=json_encode($t)?>)'>Edit</a> <a class='btn btn-sm btn-danger' href='?delete=<?=htmlspecialchars($t['id'])?>' onclick='return confirm("Delete?")'>Delete</a></td></tr><?php endforeach; ?></tbody></table></div>
<script>function edit(t){ document.getElementById('id').value=t.id; document.getElementById('category').value=t.category; document.getElementById('distance').value=t.distance; document.getElementById('fare').value=t.fare; document.getElementById('unit').value=t.unit; document.getElementById('notes').value=t.notes; }</script>
</body></html>